### ISSUE TITLE
Remarks on the 1.0.0

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#106]
Just a few remarks.

1. The sample directory. Does that serve any purpose? Otherwise, we might delete it.

2. is `publicationStmt` really a **MUST**? 
If the primary meaning is "sponsoring entity" I see many possible situations where it would not apply (people in permanent positions or independent researchers for instance). 
Further: It serves a double function as both the "entity that makes the creation of the current document possible" and "the context where it belongs". Is that a good idea? 
My suggestion would be to change the **MUST** to **MAY**.

Otherwise, we should just make it clear that it describes the context of the publication. Often that might also actually be a the institution financially sponsoring the content, but I don't know if we want to preserve that ambiguity.

**Comment by jeffreycwitt** [comment]
sample directory can be deleted. 

publicationStmt itself is a MUST according to a TEI, and according to TEI it MUST contain "ab", "authority", "distributor", "p" or "publisher" and these elements MUST become before other elements like "availability"

> It is a conformance requirement that elements supplying information about publication place, address, identifier, availability, and date be given following the name of the publisher, distributor, or authority concerned, and preferably in that order.

So if we change the presence of availability to a SHOULD or MAY, we must also allow "distributor", "p", or "publisher". If we allow all four, our processors will have to handle four different situations. 

We could change it to MUST contain either `authority` or `p`. I like P because if there is some unique situation you can always just write a prose sentence. Otherwise, I expect authority. 

We can see how well this is working and revise for 1.1.0

**Comment by jeffreycwitt** [comment]
Should this be closed? 
Should I change this to publicationStmt MUST have "authority" OR "p". I'll need to change this in the ODD as well. 
You're probably right that it is good to allow the "p" as a backup possibility.

**Comment by stenskjaer** [comment]
Sorry... That's why you should separate issues :)

I think it's a good idea to have the `p` as a fallback in case authority does not make sense, yes.

**Comment by jeffreycwitt** [comment]
@stenskjaer can you just review the changes i made and then close this. 

Basically, either pubicationStmt should take one generic P or is required to have an "authority" and "availability"

**Comment by stenskjaer** [comment]
I made two notes on a superfluous "an" . Otherwise it's good. Have you tested the RNG or should I do it?

**Comment by jeffreycwitt** [comment]
I checked, they worked for me.
