### ISSUE TITLE
Need for a comprehensive list of app types

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#17]
![img_20160618_203101](https://cloud.githubusercontent.com/assets/1146685/16204385/8cb6a75a-36ec-11e6-8f41-7aadf52b7814.jpg)

**Please add images or links to other sigla and abbreviations we need to make sure we can handle.**

Right now my proposal for handling different variants is by creating a list of `<rdg>` types. 

Each type should alert a processor to the kinds of elements, attributes, and values that will be available for processing within the `<rdg>` element. The lbp schema can also propose default and customary rendering of each `@type`, though any processor should have the freedom to experiment with its own rendering of the available data.

Keep in my mind: the `@type` should be describing a logical pattern and data structure, NOT A RENDERING. We can recommend a traditional way of rendering this data structure, however our primary job here is not to create a rendering, but to catalogue logical types of variants and the best way to structure the data that corresponds to this variant type.

**Comment by nivaca** [comment]
These come from Ockham's /Opera Philosophica.
/Cheers!
NV

**Comment by nivaca** [comment]
These come from Ockham's _Opera Philosophica_. 
Cheers! 
NV


![sigla op](https://cloud.githubusercontent.com/assets/2309005/16205114/e969626c-36e7-11e6-8fb8-e2b679ec8b8f.png)

**Comment by jeffreycwitt** [comment]
Prior to our meeting I think we need a working summary of what each of these means and maybe a couple of examples.

I propose we make a separate issue for each apparatus type. Each issue should include an initial definition and description. We can then add examples and discuss the best encoding strategy within each issue.

 I'll then use the github tags to collect all these issues into one category.

**Comment by jeffreycwitt** [comment]
I found this fairly comprehensive list today: 

http://udallasclassics.org/maurer_files/APPARATUSABBREVIATIONS.pdf

We will probably not be able to get through this whole list. I think we should prioritize "must have" apparatus type for schema 1.0.0, and then make a set of issues for types we would like to add for version 1.1.0

**Comment by nivaca** [comment]
Excellent! Cheers, Nick

On Tue, Jun 21, 2016 at 08:39, jeffreycwitt <notifications@github.com> wrote:
I found this fairly comprehensive list today:

http://udallasclassics.org/maurer_files/APPARATUSABBREVIATIONS.pdf [http://udallasclassics.org/maurer_files/APPARATUSABBREVIATIONS.pdf]

We will probably not be able to get through this whole list. I think we should prioritize "must have" apparatus type for schema 1.0.0, and then make a set of issues for types we would like to add for version 1.1.0

**Comment by nivaca** [comment]
There are some strange things in this list---things that don't match the standard use I've seen in medieval critical editions. Take e.g. the "addidit (add.)." According to the list, it's use in the same way as "supplevit (supl.)", which is not the standard use. As I've seen in medieval critical editions, "add." is used to note that a Ms. has some text which other Mss. are missing. It isn't a "suppl." (for nobody is supplying missing information) nor a correction (for in this single Ms. it doesn't appear as if the scribe corrected the text).
Nick

On Tue, Jun 21, 2016 at 08:39, jeffreycwitt <notifications@github.com> wrote:
I found this fairly comprehensive list today:

http://udallasclassics.org/maurer_files/APPARATUSABBREVIATIONS.pdf [http://udallasclassics.org/maurer_files/APPARATUSABBREVIATIONS.pdf]

We will probably not be able to get through this whole list. I think we should prioritize "must have" apparatus type for schema 1.0.0, and then make a set of issues for types we would like to add for version 1.1.0

**Comment by stenskjaer** [comment]
I would like to make my proposal of a draft of a reading type list.

As I wrote in #6 I am actually not quite convinced yet that the `@type`-tag is strictly necessary, but I am starting to lean to the usefulness of it anyway, since it removes the burden of inferring the reading type from the structure of the tags used from the processor. It also might reduce the risk of mistakes as there needs (I suppose) to be a correspondence between the declared reading type and the type implied by the structure of the tags. If they don't fit, something is wrong. Either the editor has misinterpreted the reading or his encoding does not say what he intended it to say (provided of course that the processor is bug free).

A draft of reading types:

*Corrections*

- correction_deletion
- correction_addition
- correction_transposition
- correction_substitution
- correction_restoration
- correction_cancellation

*Other (mostly error types)*

- omission
- inversion
- iteration
- alternative

These are my suggested type names. As you can see, I prefer underscores to indicate a hierarchical division (meaning that if we wanted correction_deletion_overstrike would signify a subtype of deletions). I am not sure it is better than camelcase, but I think there is a strength in having a specific sign to indicate a structural point rather than just the distinction between upper and lower case letters. 
I also prefer writing the terms in full to improve readability.
What do you think?

There are of course lots of other abbreviations in the critical apparatus (as we see in the long list that @jeffreycwitt linked, or just by glancing at the concspectus siglorum of any critical edition), but most of them don't refer to reading types. 
I am curious to see how many more you can find.

I think I will start posting issues with examples of each type later today or tomorrow, but if any of you want to, be my guest.

Related issues are #1, #4 and #6.

**Comment by jeffreycwitt** [comment]
We have attempted to solve this be reducing app types to a set of classes, variations, corrections, and conjecture. 

The rendering processor can then decide how it wants to renders these kinds of app entries.

See 1.0.0 critical guidelines Critical Apparatus section.
