### ISSUE TITLE
Word division between lines

### ISSUE THREAD

**Issue by nivaca** [lombardpress/lombardpress-schema#3]
![2016-04-18 09 09 45 am](https://cloud.githubusercontent.com/assets/2309005/14607009/654c2de4-0545-11e6-96df-7c1d3d1ddfc3.png)

Is this the right way of encoding word division between lines?

    <lb ed="#T" n="2"/>quo primo per accidens video substantiam panis in hostia consecranda eandem non video
    ho<lb ed="#T" n="3"/>stia consecrata sic hoc in proposito cum distincte diligo moraliter bonos dum quia tales unde cum me ignorante desinunt aliqui subesse huic accidenti et a me diligi illo actu

It seems a bit artificial to me.

**Comment by jeffreycwitt** [comment]
Yes, it is correct. 

I only place the hard return after the word that includes the line break rather than before. 

So for example:

    <lb ed="#T" n="2"/>quo primo per accidens video substantiam panis in hostia consecranda eandem non video ho<lb ed="#T" n="3"/>stia 
    consecrata sic hoc in proposito cum distincte diligo moraliter bonos dum quia tales unde cum me ignorante desinunt aliqui subesse huic accidenti et a me diligi illo actu

I think we should try to use the same "encodying style" as much as possible, so this is something we should try to agree on. However, it is a very small issue and it should not affect XML validation. 

The only thing we don't want to do is: 

    <lb ed="#T" n="2"/>quo primo per accidens video substantiam panis in hostia consecranda eandem non video ho
    <lb ed="#T" n="3"/>stia consecrata sic hoc in proposito cum distincte diligo moraliter bonos dum quia tales unde cum me ignorante desinunt aliqui subesse huic accidenti et a me diligi illo actu

This will add unwanted space between the "ho stia" during processing.
