### ISSUE TITLE
Use of `corr` and `subst`

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#4]
Currently the `<corr>`-tag indicates (i.e. is taken to indicate) a change, or *correction*, made by the scribe. This is in conflict with the TEI P5 guidelines, which use the `<subst>`-tag in that case, while `<corr>` signifies an editorial correction (usually inside a `<choice>`-statement).
The <subst> is a descriptive (diplomatic) element, while <corr> is a editorial (critical)
element. 

On `<subst>`, see: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PHSU and on
`<corr>`, see: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COEDCOR

I would suggest the following structure:

Example of an apparatus note stating that the scribe of witness L changes (corrects) the text from reading *intellectus* to *intelligibilia*:
```
omnia intelligiblia in eo quod sunt
<app>
  <rdg wit="#L">
    <subst hand="#h3">
      <del>intellectus</del>
      <add>intelligibilia</add>
    </subst>
  </rdg>
</app>
habent eundem modum quod Philosophus supponit.
```

My suggestion for an apparatus note where the editor has corrected the same error:
```
omnia intelligiblia in eo quod sunt
<app>
  <lem resp="#editorRef">intelligibilia</lem>
  <rdg wit="#L">intellectus</rdg>
</app>
habent eundem modum quod Philosophus supponit.
```

The `<corr>`-tag would only get into use outside the apparatus. The equivalent of the above example outside the apparatus would then be:
```
omnia intelligiblia in eo quod sunt
<choice>
  <corr resp="#editorRef">intelligibilia</corr>
  <sic wit="#L">intellectus</sic>
</choice>
habent eundem modum quod Philosophus supponit.
```

Any thoughts on that?

**Comment by jeffreycwitt** [comment]
See also issue #1 

In resolving this issue we also have the complication of deciding what to do inside an `<app>` element in a critical edition and when marking a correction in a diplomatic transcription. 

When I was using `<corr>` in the apparatus for substitutions and as a wrapper around single additions and deletions AND using `<corr>` in the diplomatic transcription, I was able to assign the `<corr>` in the diplomatic transcription an `@xml:id` and then give the `<corr>` in the apparatus ann `@corresp` attribute that pointed to the `@xml:id` of the `<corr>` in the diplomatic text.

If my recommendation in #1 for `<seg type="correction">` wrapper is accepted, do we want to wrap `<subst>` inside a `<seg type="correction">` as well as so that we can achieve the same kind of reference system. 

It starts to feel like overkill, but here's what I had in mind. 

In a diplomatic transcription, we might have: 

    <seg id="segid1" type="correction"><add place="aboveLine">im<add>portat</seg>

but in the critical apparatus we might have

      <app>
         <lem>importat</lem>
         <rdg wit="#S" type="corrReplace">
           <seg type="correction" corresp="#segid1">
                <subst>
                     <add>importat</add>
                     <del>portat</del>
                </subst>
             </seg>
         </rdg>
      </app>

Does it seem like overkill to have the `<seg>` wrapper. We could put the `@corresp` attribute on the `<subst>`?

    <app>
         <lem>importat</lem>
         <rdg wit="#S" type="corrReplace">
                <subst corresp="#segid1">
                     <add>importat</add>
                     <del>portat</del>
                </subst>
         </rdg>
      </app>

But what about in those cases where there is no substitution, such as a simple deletion or addition. In this case there would be know `<subst>` wrapper. The `@corresp` should then could go on either the `<add>` or `<del>` element, like so: 

      <app>
         <lem>fides</lem>
         <rdg wit="#S" type="corrDeletion">
              <del corresp="#segid1">non</del>
          </rdg>
      </app>

Processors will then need to know what to expect from the value of the `<rdg>` `@type` attribute to know where to expect the `@corresp` 

Alternatively if we used the <seg> element, the processor would always know where to look for the `@corresp` element on the `<seg>` element in all cases. Likewise, it would be intuitive that this `<seg>` always points to a `<seg>` element in the diplomatic transcription. It is certainly more verbose, but also more predictable and parallel. So for the above example using the <seg type="correction"> method in both cases I would imagine it looks like the following: 

In a diplomatic transcription, we might have: 

    <seg id="segid2" type="correction" subtype="corrDeletion"><del rend="strikethrough">non</del></seg>

but in the critical apparatus we might have

      <app>
         <lem>fides</lem>
         <rdg wit="#S" type="corrDeletion">
           <seg type="correction" corresp="#segid2">
                <del>non</del>
            </seg>
         </rdg>
      </app>

Another option might be to put the `@corresp` on the `<rdg>` element.
(As I write I'm starting to like this the best). 

This would look like: 

In a diplomatic transcription, we might have: 

    <seg id="segid2" type="correction" subtype="corrDeletion"><del rend="strikethrough">non</del></seg>

but in the critical apparatus we might have

      <app>
         <lem>fides</lem>
         <rdg wit="#S" type="corrDeletion" corresp="#segid2">
                <del>non</del>
         </rdg>
      </app>

But for a substitution, the processor might need to know that the `@corresp` is pointing to either or a `<seg>` or `<subst>` element in the critical editions. These two elements would be performing a logically similar function. Thus `<subst>` could be used in those cases where there is an simple substitution case, and `<subst>` should be considered identical to  `<seg type="correction" subtype="corrReplace">`

I imagine this would look like: 

In a diplomatic transcription, we might have: 

    <seg id="segid1" type="correction" subtype="corrReplace ><add place="aboveLine">im<add>portat</seg>

The ability to use seg here is helpful. Since this is certain a kind of "substitution" but in a diplomatic transcription it is not best represented with a `<subst>` tag because there actually is no "deletion". There is only the "addition" of the "im". Thus `<subst>` won't really work here because TEI demands a `<add>` and `<del>` element be present.

and in the critical apparatus we might have

      <app>
         <lem>importat</lem>
         <rdg wit="#S" type="corrReplace" corresp="#segid1">
         
                <subst>
                     <add>importat</add>
                     <del>portat</del>
               </subst>
         </rdg>
      </app>

Final note, `app/rdg` that point to corrections should only point to one witness otherwise it will be ambiguous to which element the corresponding element points.

**Comment by stenskjaer** [comment]
Please correct me if I'm wrong.
I assume that the need to make a back reference to the diplomatic transcription is because it contains more information than the critical (here which part is added and where, by who etc.).

I agree that `<seg>` and `<subst>` perform the same function in the diplomatic and critical editions respectively, and I also like the simpler critical apparatus. 

I'm not sure there will be a risk of ambiguity of the `@corresp` here, because it only points one way, right. From the `<rdg>` to the `<seg>`. Since the `@corresp` points to an ID, I don't see the need for a parallel structure.

I would therefore tend to vote for the second solution, using `<seg>` to encapsulate the whole expression in the diplomatic edition and the `<subst>` to express the more abstract concept of correction with a reference to the related segment in the diplomatic edition.

An addition: The `@corresp` attribute should of course be facultative, right (*MAY* in the documentation)? What I'm asking is: There is no need for a diplomatic edition as basis for the critical, right?

**Comment by jeffreycwitt** [comment]
Michael's completely correct and we have adopted `subst` instead of `corr`. We also allowed for the possibility of `<seg type="correction">` in the diplomatic transcription. We may want to review how well this is working when review the guidelines for 1.1 release.
