### ISSUE TITLE
A type question: Substition or variant

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#50]
Take this passage:

![skaermbillede 2016-08-04 kl 15 07 00](https://cloud.githubusercontent.com/assets/4047523/17402805/4190977c-5a55-11e6-9671-db47f6097be2.png)

I read the text around the arrow like this in the diplomatic transcription:
``` xml
quid continuum et <add place="above">vel</add>
<lb ed="#M"/> temporale
```
I interpret this to mean that the scribe wants to replace the "et" with a "vel". But it is not indicated clearly (no deletion of the "et").

So how would you encode it critically?
Either I could consider it a `variation-substance` or a `correction-substitution`. I clearly interpret it to be a correction, but that is difficult to encode.
For example:
``` xml
<app>
  <lem>vel</lem>
  <rdg wit="#M" type="corrections-substitution">
    <subst>
      <del>et</del> <!-- NOT GOOD, there is no deletion -->
      <add place="above">vel</add>
    </subst>
  </rdg>
</app>          
```

But encoding it as a variant is also unsatisfying (partly because there only is one witness).
``` xml
<app>
  <lem>vel</lem>
  <rdg wit="#M" type="variation-substance">et <add place="above">vel</add></rdg>
</app>
```
But that is also very unsatisfactory.

Any thoughts?

**Comment by jeffreycwitt** [comment]
My first inclination would have been to do what you did in your first example:

```xml
<app>
  <lem>vel</lem>
  <rdg wit="#M" type="corrections-substitution">
    <subst>
      <del>et</del>  
      <add place="above">vel</add>
    </subst>
  </rdg>
</app>  
```
In this case, I think `<del>` is correct because `<del>` actually reflects what the scribe wanted here. The difference from more common substitutions is simply in the material rendering. Most often a "deletion" will be indicated with a strikethrough and then the added word. But in this case, it seems that the scribe thought simply adding the new word above the word to be deleted was a sufficient material indication that "et" should be replaced with "vel".

This is on the assumption that this really should be understood as a correction. This seems to me to be a decision for the editor to make. Given that the "hand" doesn't seem to change. I would see this as mostly likely a correction rather than just an alternate reading. 

However, this issue did come up at the DLL meeting. The case in question was very similar to the case you described except that the "addition" was made by another hand. The other DLL editors insisted that this should not be seen as a correction, but as simply a suggestion of an alternate reading. (You sometimes also see this inline, where a scribe is not sure what the right word is. Thus they will write "sed vel secundum" to mean the correct reading is one of these two words.)

For this situation, I was wondering if might be possible to create a new "variation" type called "variation-choice" which might be encoded as follows:

```xml

<rdg wit-"#G" type="variation-choice">
   <choice>
       <orig>et</orig>
       <add hand="#newHand>vel</add> <!-- strictly speaking TEI does not allow <add> inside choice, so maybe we could use <seg> -->
      <!-- and it seems like multiple adds or segs could go here -->
   </choice>
</rdg>
```

Another approach (that I don't like as much) would be to treat each hand as a separate reading. But this would require us to treat each hand in a manuscript as a separate witness. But I think our current approach has been to think of the material codex as a distinct witness and to treat the different hands as "changes" that belong to a given witness. Likewise, on this approach, how would we deal with a "choice" structure like the one described above where the same hand is used? This would require us to have two different readings for the same hand, which I don't like.

**Comment by stenskjaer** [comment]
I see the point with the possible variant reading (which might also be an interpretation of this situation). And actually I understand the need of being able to say "here we actually have to possible readings, but no choice has been made between the two in the witness".
And I like the idea with the `choice` element. I wonder whether we might use `<seg>` in stead?

Example:
``` xml
<rdg wit-"#G" type="variation-choice">
   <choice>
       <seg>et</seg>
       <seg hand="#newHand">vel</seg>
   </choice>
</rdg>
```
`<seg>` is allowed in `<choice>` and it can have `@hand`. Then there is no need of indicating a chronology that might not be relevant to the information conveyed in a situation where no correction takes place.

Another thing: How does this differ from the `variant-substance`? By not being a variant between two or more witnesses?

**Comment by jeffreycwitt** [comment]
I think agree. Though in the case of your example, if the hands are actually the same, it might still be nice to indicate which "seg" was the original and which one was added outside the main line. 

(Can `seg` also take an `@place` attribute?)

Ideally it might be nice to support both:

```xml
<choice>
    <orig></orig>
    <seg></seg> 
</choice>
```
and

xml```
<choice>
   <seg></seg>
   <seg></seg> 
</choice>
```

This differs from `variation-substance` because we are not separating these into different readings. 

Basically, we're assuming that each manuscript has only ONE reading, and then we're saying that the `rdg` in manuscript G offers two (or three) alternative choices. 

Some of the DLL editors, prefer to see each hand as offering a different reading. On this approach, they would likely make a new <rdg> for each possibility even if it falls in the same manuscript or material witness. While sensible, I think this brings in new problems and I presently prefer the former approach.

In short I think there are different ways we can understand the "term" witness and its connection to `<rdg>`. I currently like our approach of thinking about a witness as a distinct material artifact which offers one `<rdg>`, even if many hands have contributed to that witness. We can then describe the various actions different hands have taken within a given `rdg` element. 

Both approaches probably work and have pros and cons. I think the most important thing is to be rigorously consistent in our modeling.

**Comment by stenskjaer** [comment]
A `seg` can't have `@place` but it can contain pretty much any element. I know it might seem like overkill but something like this could work:
``` xml
<choice>
   <seg>et</seg>
   <seg><add place="right-margin">vel</seg> 
</choice>
```
So, you might ask yourself, why don't I just accept the use of `orig` and `seg`. Well, I guess I could, but it seems to distort the picture a bit since there is no element opposing the `orig`. Although you might argue that it necessarily follows that what is *not* original is a later addition, but that is not indicated in the semantics of the tag. I don't feel the same semantic strain between the regular text and some latter being `add`ed.
Furthermore, quoting from the Guidelines, this use of of `orig` seems to be slightly off the intended meaning of the element:
> `<orig>` (original form) contains a reading which is marked as following the original, rather than being normalized or corrected.

I read this to mean that it indicates a relation between the witnessed text and *editorial* changes.

Another possibility is to use the `@n`. But maybe we should be careful giving that attribute too many functions depending on context.

I thought about the double reading situation and wondered whether you could do something like
``` xml
<app>
  <lem>something</lem>
  <rdg wit="#M" type="variation-choice">
    <rdg>et</rdg>
    <rdg>vel</rdg>
  </rdg>
</app>
```
Aside from maybe being unintuitive, it also won't work as the `rdg` cannot contain itself.
I don't like the idea of registering different readings in one manuscript as different witnesses (which is basically the consequence of splitting it into two readings). But I understand the terminological challenge of a witness presenting several equivalent readings.
Although I'm not sure I agree with the last part of your statement (emphasized) that 
> I currently like our approach of thinking about a witness as a distinct material artifact *which offers one `<rdg>`, even if many hands have contributed to that witness*.

I find it important to stress that one physical artefact is one witness. But it seems to me that one witness can present alternative readings.

I get the impression that we both see the strength in having a variant type to reflect that. The problem is mostly how it is encoded.

On the alternative witness approach. I guess this is how you would encode it as if it each reading were a separate witness when it is the same hand:
``` xml
<app>
  <lem>vel</lem>
  <rdg wit="#M" type="correction-choice">et</rdg>
  <rdg wit="#M" type="correction-choice">vel</rdg>
</app>   
```
This seems to me to be slightly nonsensical. If I didn't know better I would take this to be a encoding mistake. 

Having typed that out I clearly think it better to keep the alternative readings inside a common `rdg` element (they might be different readings, but not different witnesses). And I think that the appropriate type and use of `choice` and `seg` would be sufficiently neutral. Inside the `seg`s any sort of element can then be used to indicate order, addition or what not. 

That is my take on it, but then again: If you have strong feelings about including the `orig` I really won't oppose it.

**Comment by jeffreycwitt** [comment]
I think we're in agreement, I have no strong feelings about `<orig>` whatsoever. I'm just grasping for someway to record a kind of logical order for the alternatives presented. 

Regarding this: 
>I find it important to stress that one physical artifact is one witness. But it seems to me that one witness can present alternative readings.

I see this, but this sort of goes against our approach of having one `<rdg>` and then indicating additions by other hands with `@hand` placed on the `<add>` element, as opposed to create a new `<rdg>` 

Further, we have a problem in the header. 

Assuming witness refers to one material artifact in the header, it becomes difficult to do the following:

```xml
<app>
  <lem>vel</lem>
  <rdg wit="#M" type="correction-choice">et</rdg>
  <rdg wit="#M1" type="correction-choice">vel</rdg>
</app> 
``` 

If you wanted to do this, wouldn't you have needed to introduce a `witness` in the TEI Header for both M and M1. But M1 is not a unique artifact, it is simply a hand in witness M. 

(Maybe I'm assuming too close a connection between `witness` in the source description and `@wit` as an attribute of `<rdg>`. )

(We can also talk about this a bit more when we meet next week).

**Comment by stenskjaer** [comment]
I agree that the parallel readings of same witness won't work. Even when you differentiate between M and M1, because basically there is no difference. Same manuscript, same scribe (slightly different situation if it was a different hand, but still). To me the encoding with two parallel readings referring to the same witness seems absurd or at least impossible. They could be differentiated if there were different hands, but I still wouldn't agree in considering a different hand a different witness. BTW I think your assumptions on the relation between `witness` and `@wit` are correct. So we agree completely on that.

Just to get the reading discussion straigt: I *don't* want any parallel `rdg` elements coming from the same witness (like in the example you just repeated). But the only way around this where we can still keep two or more alternatives alongside each other without necessarily imposing assumptions about choice or preference from the scribe is by using the `seg` elements, possibly with `add` or `@n` to indicate the material chronology and spatiality of the text (or alternatively the `orig` element).

So do we agree on something like:
``` xml
<app>
  <lem>vel</lem>
  <rdg wit="#G" type="variation-choice">
    <choice>
      <seg>et</seg>
      <seg>vel</seg>
    </choice>
  </rdg>
</app>
```

Rules:
- `rdg` **MUST** contain a `choice` element.
- `choice` **MUST** contain two or more `seg` elements.
- `seg` elements **MAY** use `@n` to indicate their relative order when they both are written on the same baseline.
- A `seg` element **MAY** contain an `add` element to indicate whether and where it has been added, when it is not on the baseline of the text.
- `seg` or `add` **MAY** use `@hand` to indicate an alternative scribe.

In this way there is *only*  one witness, the physical manuscript, but leaving the possibility of several scribes.
Could it be a way to go? Will that leave the markup clear enough in itself?

**Comment by jeffreycwitt** [comment]
Found a really good example use case for this in Wodeham editions

In this example M and V have the correct reading "instare"
S originally had "dicere" and then corrected it to "instare"
T includes both "dicere" and "instare" as options, but isn't sure which one is correct and simple writes "dicere vel instare".

I encoded this as follows:

```xml
<app>
  <lem wit="#M #V">instare</lem>
  <rdg wit="#S" type="correction-substitution">
    <subst>
       <del>dicere</del>
       <add>instare</add>
    </subst>
  </rdg>
  <rdg wit="#T" type="variation-choice">
     <choice>
       <seg>dicere</seg> <!-- actual line in T is "dicere vel instare" -->
       <seg>instare</seg>
     </choice>
   </rdg>
</app>

**Comment by stenskjaer** [comment]
I like this! And if you insist on making clear that materially it says "dicere vel instare" you either indicate that in your diplomatic transcription or make a note here.
To me this looks like the way to do it!
I will use your example when I add it to the guidelines.

**Comment by stenskjaer** [comment]
I have just posted a PR on this, but as I wrote that draft, I became in doubt whether there should also be a reflection of this in the diplomatic, but I am inclined to think that there should not. 

Either you have both readings present in the same baseline, and then you would just transcribe that, or the one is added above the line, and then it should maybe be transcribed as an addition above line. But I don't know. Maybe it also has a place in the diplomatic?
