### ISSUE TITLE
citation, ref, quote, and bibl needs more clarity in documentation

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#54]
I received the following email asking for more clarification about apparatus fontium elements.

I am curious about your recommendations / usage regarding `<bibl>` (and `<ref>`) in `<cit>`, and the examples given do not answer my question. Do you encode in `<bibl>` only what is actually present in your text, or do you use it to provide the full reference to the quoted extract?
In other terms, if you had for instance in a text:

Bernardus : Auferatur malus ne generet malos. Non potest arbor mala fructus nisi malos facere.

Would you encode it like this:

``` xml
Bernardus : <cit>
                  <quote>Auferatur malus ne generet malos. Non potest arbor mala fructus nisi malos facere.</quote>
                  <bibl><author>Bern.</author>, <title>Epist.</title>, 102 (VIII, 257-8)</bibl>
               </cit>
```

Or like this:

``` xml
               <cit>
                  <bibl>Bernardus :</bibl>
                  <quote>Auferatur malus ne generet malos. Non potest arbor mala fructus nisi malos facere.</quote>
               </cit>
```

and maybe put the bibliographic reference in a note inside `<cit>`?

**Comment by jeffreycwitt** [comment]
I responded with the following clarification, which needs to make its way into the official documentation: 

We use `<ref>` to encode the reference made by the original author and `<quote>` to encode the original quotation.

`<bibl>` is reserved for the modern editor's attempt to encode a modern reference identification for the quotation and is only allowed inside a `<cit>` wrapper.

A `<cit>` element can wrap around either a `<ref>` or `<quote>` and should be used anywhere an editor wants to record what would usually appear in the apparatus fontium.

We do this because there are basically three phenomena we're trying to deal with.

1) A basic reference to quotation or passage without actually including a quotation.
2) A quotation without any original reference.
3) A quotation with an original reference.

If we're dealing with case 1, we would do:

```xml
<p>
Pater per
  <cit>
    <ref ana="#aug-cd-10_1"><name>Augustinum<name> in libro X <title>de Civitate</title></ref>
    <bibl><author>Augustinus</author>, <title>De civitate Dei</title>, X, c. 1 (PL XX:XX)</bibl>
  </cit>
</p>
```

If we're dealing with case 2, we would do:

```xml
<p>
  <cit>
    <quote ana="#aug-cd-10_1">lorum ipsum lorum ipsum</quote>
    <bibl><author>Augustinus</author>, <title>De civitate Dei</title>, X, c. 1 (PL XX:XX)</bibl>
  </cit>
</p>
```

For case 3, which is the closest to the example you gave, we would encode both the `<ref>` and the `<quote>`, but only the `<ref>` or the `<quote>` should be wrapped in a`<cit>` element and not both. We recommend citing the `<quote>` since we see this as primary. We would then associate the the `<ref>` with the `<quote>` it is related to via the `@corresp` attribute. The reason we don't wrap all of this within one `<cit>` element is that we have many cases in which the original `ref` is in a position quite far away from the quote. (E.g. the reference may be made at the beginning of the paragraph while the quote only appears at the very end.) So, we encode case 3 as follows:

```xml
<p>Patet per
  <ref corresp="#quote1">
    <name>Augustinum<name> in libro X <title>de Civitate</title>
  </ref>
  dicit quod:
  <cit>
    <quote xml:id="quote1" ana="#aug-cd-10_1">lorum ipsum lorum ipsum</quote>
    <bibl><author>Augustinus</author>, <title>De civitate Dei</title>, X, c. 1 (PL XX:XX)</bibl>
  </cit>
</p>
```
So, I would encode the example you gave as follows:

```xml
<ref coresp="#quote1"><name>Bernardus</name></ref>:
<cit>
  <quote xml:id="quote1">Auferatur malus ne generet malos. Non 
  potest arbor mala fructus nisi malos facere.</quote>
  <bibl><author>Bern.</author>, <title>Epist.</title>, 102 (VIII, 257-8)</bibl>
</cit>

```

As you can see, we also hope to have an `@ana` tag identifying this quotations as instance of a canonical quotations. (This works best right now with bible verses since bible verses come with a fairly standard reference system.)

In the end our goal will be able trace the history of how references were made throughout the 500 years of commenting on the Sentences. This encoding pattern should allow us to query for any `quote` that is an instance of `aug-cd-10_1` (or `gen1_1`) and ask if there was a corresponding reference and then ask for how they reference appears. Using other data, we can then group references by century of creation, or the region in which the author was working, or the religious order of the author.

**Comment by stenskjaer** [comment]
I agree with your explanation and find the distinction between the three different situation good.

I only see one problem (which is also not addressed by our current guidelines, and which is slightly beside the issue here): As it is now, we only present examples where the presentation of the reference is hard-coded. 
Of course it might differ between use cases, but I find it important to be able to separate content from presentation, also when it comes to the encoding of references.

As you indicate, it might be possible to use the `@ana` to indicate a canonical reference that might be used in formatting the reference during processing. The problem, as we have also talked about, is that the canonical references might not correspond exactly to the references that you also need for the passage.

Maybe we could solve it by indicating reference patterns that can be used by the processor, and that could solve the problem with the reference not corresponding exactly with the canonical reference. I have several thoughts about this. I'm not sure whether we want to include that in the schema (or maybe rather 1.1 or later), or whether you should implement that on your own and keep it out of the schema. Also, I realize that this is not necessarily a part of the discussion, so let me just say that I agree very much with your description above. 
But if you think it would be worth trying implementing also a presentation-agnostic encoding of references, I could make a suggestion in a different issue.

**Comment by jeffreycwitt** [comment]
Marjorie Burghart hopes to reference this part of our guidelines in a chapter that will appear in Summer of 2017. This is a reminder that I need to complete this issue well before that time and that the commit for this issue should be send to Marjorie for review before the final merge.
