### ISSUE TITLE
Indicate alternative readings in critical apparatus

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#67]
I ran into the situation today that I wasn't quite sure how to read a word and would like my reader to know of my incertainty (even in the critical text). I therefore wonder whether we might want to introduce a use of a combination of the `<choice>` and `<unclear>` elements. The problems is of course what you might want to call that reading type.

This situation is different from the one in #50 because this indicates the doubt of the editor rather than the scribe.

Take this example:
![skaermbillede 2016-10-05 kl 16 11 56](https://cloud.githubusercontent.com/assets/4047523/19116641/89b82a28-8b16-11e6-94aa-03f767f4c488.png)

The problem is whether it reads _haec_ or _hoc_ at the arrow. I would encode this like so:

``` xml
et intelligimus, et
<app>
  <lem>haec</lem>
  <rdg wit="#V">
    <choice>
      <unclear cert="high">haec</unclear>
      <unclear cert="mid">hoc</unclear>
    </choice>
  </rdg>
</app>
```

Which for instance could result in the following apparatus entry:

> haec ] haec _vel fortasse_ hoc V

If this were adapted, would it then qualify as a new reading group? I am slightly hesitant as _entia non multiplicanda sunt sine necessitate_.

**Comment by nivaca** [comment]
I like it (even as an Ockhamist)!

--
Nicolas Vaughan
Profesor
Departamento de Filosof?a
Universidad de los Andes
Bogot?, Colombia
On Wed, Oct 05, 2016 at 9:21am, Michael Stenskjaer Christensen <notifications@github.com<mailto:notifications@github.com>> wrote:


I ran into the situation today that I wasn't quite sure how to read a word and would like my reader to know of my incertainty (even in the critical text). I therefore wonder whether we might want to introduce a use of a combination of the <choice> and <unclear> elements. The problems is of course what you might want to call that reading type.

This situation is different from the one in #50<https://github.com/lombardpress/lombardpress-schema/issues/50> because this indicates the doubt of the editor rather than the scribe.

Take this example:
[skaermbillede 2016-10-05 kl 16 11 56]<https://cloud.githubusercontent.com/assets/4047523/19116641/89b82a28-8b16-11e6-94aa-03f767f4c488.png>

The problem is whether it reads haec or hoc at the arrow. I would encode this like so:

et intelligimus, et
<app>
  <lem>haec</lem>
  <rdg wit="#V">
    <choice>
      <unclear cert="high">haec</unclear>
      <unclear cert="mid">hoc</unclear>
    </choice>
  </rdg>
</app>

Which for instance could result in the following apparatus entry:

haec ] haec vel fortasse hoc V

If this were adapted, would it then qualify as a new reading group? I am slightly hesitant as entia non multiplicanda sunt sine necessitate.

-

**Comment by jeffreycwitt** [comment]
We've resolved this here: [https://github.com/lombardpress/lombardpress-schema/blob/ca5b01e/docs/1.0/critical/index.md#variation-choice](https://github.com/lombardpress/lombardpress-schema/blob/ca5b01e/docs/1.0/critical/index.md#variation-choice)
