### ISSUE TITLE
@ed does not take a pointer

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#76]
I just noticed that the datatype of the `@ed` attribute that we use on `pb` and `cb` elements does not take a pointer but "1–∞ occurrences of teidata.word separated by whitespace". This means that giving sigils in hashtag format (e.g. "#D") is invalid.

Should I submit a PR with update the docs in accordance with that?

**Comment by jeffreycwitt** [comment]
Ugg. Has that alway been the case? Weird.

I would prefer to be using a pointer that expects a declaration in the sourceDesc of every document. I would like the references to be analogous to our use of `@wit` wit `<lem>` and `<rdg`> elements. 

It looks like there is something called `@edRef` which is identical to `@ed` except that it can contain a pointer.

See http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.edition.html

That's going to be a lot of changes. I have thousands of line breaks with pointers.

Still I think it's important to get it right and follow the wishes of the larger community.

Doesn't it also seem like a bug in the TEI schema, since TEI gives us no error when we use pointers as the value of the `@ed` attribute.

**Comment by stenskjaer** [comment]
I know this sucks. I think it has always been like that. I found the problem because I have been validating an encoding with our RNG-schema. So at least in my environment it alerts you of the violation.

I did see the `@edRef` but it seems a bit strange to me to have to create another attribute so allow for a pointer. On the other hand, I suggests that there is a specific and good reason for having *word* as datatype on the `@ed` (although it escapes me!).

**Comment by jeffreycwitt** [comment]
@stenskjaer see this response from @lb42 https://github.com/TEIC/TEI/issues/1537#issuecomment-260127585

**Comment by stenskjaer** [comment]
I suppose that means that we do not need to update the documentation on this point.

**Comment by stenskjaer** [comment]
I had another look at this. Turns out that what I interpreted as a problem with the schema was caused by a bug in the nXML-mode in emacs that does the validation (seems it does not validate the attribute pattern "\p{L}|\p{N}|\p{P}|\p{S})+" correctly). This is pretty annoying because it indicates that several correct things are invalid. I have filed a bug-report with the Emacs developers and hope for a positive answer some day, but close this for now.
