### ISSUE TITLE
Meaning of the bibl-element

### ISSUE THREAD

**Issue by stenskjaer** [lombardpress/lombardpress-schema#87]
What does the `bibl` element actually mean when we use it in the *apparatus fontium*? Take the following simple example:

``` xml
Pater per
<cit>
  <ref><name>Augustinum<name> in libro X <title>de Civitate</title></ref>
  <bibl><author>Augustinus</author>, <title>De civitate Dei</title>, X, c. 1 (PL XX:XX)</bibl>
</cit>
```
It is clear here that the `bibl` contains a reference to *one* bibliographic entity. But as it is specified, the field might be more ambiguous. The the development EAD of the documentation now has the following:

> `<bibl>` is reserved for the modern editor's attempt to encode a modern reference identification for the quotation. `<bibl>` is only allowed inside a `<cit>` wrapper.

In my processing script I interpret this to mean that the `bibl` element is where I put the text that I want to print after the reference to the `ref` or `quote` in the *apparatus fontium*. From a functional point of view, this means that it seems natural to print something like the following example:
``` xml
sic, cum <name ref="#Aristotle">Philosophus</name> ponit
<cit>
  <quote type="paraphrase">
    species abstractas a phantasmatibus intelligibiles
  </quote>
  <bibl>
    Locus non inventus, sed vide <name ref="#Aquinas">Aquinas</name>, 
    <title ref="#Aquinas.SentDA">Sent. de anima</title> Lib. 3, cap. 4, p. 218, 
    ll. 8--23 et p. 220, ll. 101--121, et confer <name ref="#Aristotle">Arist.</name>, 
    <title ref="#Arist.DA">De anima</title> III.8 432a8-9: "Necesse est quemcumque 
    intelligentem phantasmata speculari."
  </bibl>
</cit>
```
This will produce a nice apparatus entry, but the semantics of the element are clearly not respected, as it contains references to two bibliographic entities and three different passages.
I see two different possibilities:
1. Pretend this isn't a problem. 
2. Use the `listBibl` element when the entry contains more than one bibliographic entry.

Intuitively solution 1 seems bad. The idea of semantic markup is the possibility of using the data flexibly according to context and need based on the assumption that the content conforms with the specification of the markup. 
But solution 2 seems just as bad. The `listBibl` implies that the child elements are *only* separate `bibl` entries, which makes the kind of explanatory notes used in my example impossible.

Solution 2 might be better than 1, though. According to the guidelines (http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-listBibl.html) the `listBibl` can contain `head` (but not `p`). This shows that it can contain elements that are not strictly speaking bibliographic entities. Does it follow from that that we could also use free-floating text-nodes to act as general text? I am not sure, as the `listBibl` is not a text block, but a list element. So it has none of the core text encoding elements available...

A third solution would be to encourage the use of `p` in `cit` for encoding the bibliographic note (which in effect is a paragraph-like think, if we consider it a note). This would make the following encoding possible (and valid):
``` xml
sic, cum <name ref="#Aristotle">Philosophus</name> ponit
<cit>
  <quote type="paraphrase">
    species abstractas a phantasmatibus intelligibiles
  </quote>
  <p>
    Locus non inventus, sed vide 
    <bibl>
      <name ref="#Aquinas">Aquinas</name>, <title ref="#Aquinas.SentDA">Sent. 
      de anima</title> Lib. 3, cap. 4, p. 218, ll. 8--23 et p. 220, ll. 101--121
    </bibl> 
    , et confer 
    <bibl>
      <name ref="#Aristotle">Arist.</name>, <title ref="#Arist.DA">De anima</title> III.8 
      432a8-9: "Necesse est quemcumque intelligentem phantasmata speculari."
    </bibl>
  </p>
</cit>
```
This still somewhat conflates the concept of bibliographic entry and reference, as these *stricly speaking* are references rather than bibliographic entries (and the two different references to Aquinas *Sententia de anima* are this kept in one element). 
Using a `<ref>` with a unique or canonic reference (via `@ana` or whatever) may solve this ambiguity (for purposes of indices etc.). But that's slightly tangential to this discussion, I guess.

I now tend to favour solution 3, despite the added complexity, as it is semantically much clearer. `p` might not be the best element, but since `note` is already in use in this context, this was my first idea. Alternatives are welcome.

So, any good objections against or improvements of solution 3?

**Comment by jeffreycwitt** [comment]
Apologies for the delayed response to this great issue. 

Basically, I like option three with a couple of caveats and modifications. 

In my view, the example you give, despite having "bibliographic" features, is not strictly a source identification for the quote in question. 

In this case, it is actually more of an editorial note indicating that a precise reference cannot be found and that the reader may what to consult one of several related places.

Our guidelines already allow that `<cit>` may take a `<note>`. I see `<note>` functioning parallel to your use of `<p>`, and `<note>` can also take `<bibl>` elements as children.

Nor do the guidelines demand that a `<bibl>` is present. 

Therefore, in general I would expect the following behaviors:

- if a reference can be found for a quotation, the editor will offer a `<bibl>` as a direct child of the `<cit>` directly after the `<quote>`
- if the editor wants to add a further explanatory note, that may or may not include other bibliographic references, this should be included in a `<note>` element as a direct child of `<cit>` and following the `<bibl>` element. The `<note>` may contain further semantic markup such as subsequent `<bibl>`s, but for the purposes of uniform processing we should severely limit the expansiveness of markup up within the note. (I'm also inclined to limit the allowed numbers of `<bibl>` to one, since this would indicate the editor's preferred or canonical reference. Other related references, perhaps to other editions, etc, could be indicated with the prose `<note>`.
- if a bibliographic reference for a quotation cannot be found, no `<bibl>` should be included. In this case, if the editor wants to leave a note about possible locations or simply note that no attribution can be found, this should be placed in a `<note>` element directly following the `<quote>`.

From a processing point of view, I'm generally assuming that the processor will first target the canonical `<bibl>`, print the value of the `<bibl>`, then add a "period" (or other separating punctuation) and then print the contents of the note. Something like: 

> Aquinas, Sent. I, d. 2, q. 1. Cf. Aquinas Sent. I, d. 3, q. 2 and q. 4

Everything before "Cf." was in the `<bibl>` element. "Cf." and following would be in the `<note>`

Thoughts?? 

If we agree, let's add a version of this explanation to the documentation.

**Comment by stenskjaer** [comment]
You are right in you observation that my introduction of `<p>` is actually parallel to the current `<note>` which should just be used in stead. I agree completely with that. 

Thoughts about a list of allowed elements in the `<note>`:
- `bibl`: bibliographic references.
- `quote`: quotations
- `mentioned`: words occurring in the edited text
- `ref`: references to other parts of the edited text
- `p`?
Other?

I also tend agree that the `cit` can only contain one `bibl`, as *that* is the reference.

**Comment by jeffreycwitt** [comment]
@stenskjaer I think we are in agreement here, but the there is no entry in the guidelines for the use of `note` within the `cit`, so we need to add this. 

TODO: add `cit/note` section with description, rules, and examples.
