### ISSUE TITLE
A correction that varies

### ISSUE THREAD

**Issue by jeffreycwitt** [lombardpress/lombardpress-schema#91]
I would like to propose the idea of a "correction that varies" and to distinguish this from the case of a "variation with correction" described in issue #82. 

See picture at the bottom of this issue for an illustration.

A "correction that varies" only seems possible in the `correction-addition` and `correction-substitution` case. 

At present our guidelines state for a simple correction-addition:

```xml
<app>
  <lem>Filii et</lem>
  <rdg type="correction-addition" wit="#V"> 
     <add place="above-line">Filii et</add>
  </rdg>
</app>
```
and it is suggested that this should render as: 

>Filii et] *add. s.l* V

But what if the correction was: "Filium etiam" or "Filium et". The processor would not necessarily know that this is a correction to something different than the lemma. Such cases should ideally be render as: 

>Filii et] Filium etiam *add. s.l* V

Reflecting on this it occurs to me that "correction-addition" and "correction-substitutions" that DO NO vary will have values of `<add>` that are identical to `<lem>`. 

So what if changed the guidelines a bit, such that in the `<add>` in basic corrections should be empty (or it could have a `@copyOf` attribute, which require an ID or xpath to the `lem`). In this way, <add> contains a text value, the processor would know that this is a "correction that varies".

Thus I would re-write the normal correction-addition as: 

```xml
<app>
  <lem>Filii et</lem>
  <rdg type="correction-addition" wit="#V"> 
     <add place="above-line"/>
  </rdg>
</app>
```

and write the other cases as: 

```xml
<app>
  <lem>Filii et</lem>
  <rdg type="correction-addition" wit="#V"> 
     <add place="above-line">Filium etiam</add>
  </rdg>
</app>
```

or 

```xml
<app>
  <lem>Filii et</lem>
  <rdg type="correction-addition" wit="#V"> 
     <add place="above-line">Filium et</add>
  </rdg>
</app>
```

![img_20170217_111610](https://cloud.githubusercontent.com/assets/1146685/23073178/a726f796-f502-11e6-9d4e-e055bc1ceea1.jpg)

**Comment by stenskjaer** [comment]
Conceptually I think this is a good distinction to make. I don't quite know how I feel about the empty elements. Especially to have an `<add>` element that is empty seems intuitively odd. I wonder whether it might be a bit difficult to explain and sell this solution, as it might seem unnatural.

But the distinction should definitely be made. I have been wondering how explicit we have been about the relation between lemma and readings. Are you allowed to treat the lemma as a reading (giving it any reading type and ascribing it to witnesses like this:
```xml
<app>
  <lem type="correction-addition" wit="#V">
    <add place="above-line">Filii et</add>
  </lem>
</app>
```
In any critical note there will be a redundancy when the content of one `rdg` element is identical to the content of `lem`. Since a lemma is (often) nothing more than the accepted reading, might we not just take the consequence of that?

Then the distinction from the alternative case with the correction that varies is immediately distinguishable from the addition that is the accepted text.

**Comment by jeffreycwitt** [comment]
Decision: Add the concept of correction that varies to documentation with instructions about a processor should should for identical string values between the `<add>` and `<lem>` to differentiate between a simple correction-addition and a correction-addition that varies.
